### ISSUE TITLE
Change the window manager 

### ISSUE THREAD

**Issue by Yisus7u7** [Yisus7u7/termux-desktop-lxqt#1]
@suhan-paradkar
@librehat

Currently I have it configured with xfwm4, since there works the composer, I plan to migrate to openbox as it allows to customize more, to one that presented the following problems : 

1- openbox consumes a little more resources, but well, this is not serious, it is only optional, the most serious is this :  

2- In openbox there is no composition, without the composer you can not add transparency effects, and I do not see that option for openbox, that makes the user have to install gtk themes and the xfce4 theme changer, to be able to change the layout of the top of the windows

**Comment by Yisus7u7** [comment]
@suhan-paradkar @librehat

I already fixed it and changed it to openbox, I found this composer : 

xcompmgr

They're going to love animations, a one that's a little slow, if you know how to speed them up a little I'd appreciate it, fixed

**Comment by Yisus7u7** [comment]
Please, if you can help me increase the speed of the animations, I would appreciate them, so far this is already fixed Please, if you can help me increase the speed of the animations, I would appreciate them, so far this is already fixed.

**Comment by suhan-paradkar** [comment]
You can use the compositor configuration itself to do that...

**Comment by Yisus7u7** [comment]
But I don't see a way to change speed
