### ISSUE TITLE
WARNING: linker: Warning: unable to normalize 

### ISSUE THREAD

**Issue by Learn-Termux** [Yisus7u7/termux-desktop-lxqt#14]
**To Reproduce**
1. Entering any commends .(Like ls ,cd,pkg)

**Expected behavior**
shows
```
WARNING: linker: Warning: unable to normalize ""
```
**Screenshots**
![Screenshot_20211112-145408](https://user-images.githubusercontent.com/91124025/141444408-d111c9cb-7a90-4ab1-9459-cb9b746a0143.jpg)
![Screenshot_20211112-150129](https://user-images.githubusercontent.com/91124025/141444456-cbb1c4b7-a7cc-44fb-88e3-20b5a7d5e9b0.jpg)
![Screenshot_20211112-150220](https://user-images.githubusercontent.com/91124025/141444568-d9d630f8-df61-4363-b640-15f18700477e.jpg)

**Desktop :**
 - OS: [Android]
 - Browser [chrome]
 - Version [7.1.1]

**Smartphone :**
 - Device: [Samsung J2]
 - OS: [Android]
 - Browser [chrome]
 - Version [7.1.1]

**Comment by Yisus7u7** [comment]
That issue isn't related to this repository, it's an issue termux had during the ndk update.

**Comment by Yisus7u7** [comment]
Try updating your packages:

pkg update && pkg upgrade

In case you have outdated packages without updating

**Comment by Yisus7u7** [comment]
Try running this:
```
pkg up
pkg i termux-elf-cleaner
termux-elf-cleaner $PREFIX/lib/libc++_shared.so```

If the problem persists, report it to Termux :  

https://github.com/termux/termux-packages/issues

**Comment by Learn-Termux** [comment]
It is happens only on your lxqt version 2.1.3.


I reinstalled the termux and try to install xfce and lxqt of your old version.
But the error doesn't appers.
Finally I reinstalled termux again ,and i installed lxqt current version , 
It shows ``` WARNING: linker: Warning: unable to normalize "" ```

**Comment by wfwz** [comment]
![38ffc735da44f5aa5ef90f369c57e1f](https://github.com/Yisus7u7/termux-desktop-lxqt/assets/159263054/9aef4e4d-c59f-4aea-b127-6df0b89065dc)
这该怎么办    求求
