### ISSUE TITLE
Add music player 

### ISSUE THREAD

**Issue by Yisus7u7** [Yisus7u7/termux-desktop-lxqt#2]
I'm going to work on this, I want to use qt5 but I don't see a way to do it

**Comment by Yisus7u7** [comment]
We can use this, but you have problems with gstreamer:
https://github.com/andreisergiu98/music-player-qt5

**Comment by librehat** [comment]
Please if you have package request, send it to x11-packages repo. I'll try to add https://audacious-media-player.org/ in the next few days

**Comment by Yisus7u7** [comment]
I know, but I'm compiling and testing several to choose which one works best

**Comment by Yisus7u7** [comment]
I found something better, he's going to love it, and if it works, I'll report it to x11-repo

**Comment by librehat** [comment]
https://github.com/termux/x11-packages/pull/350

**Comment by Yisus7u7** [comment]
![Screenshot_20210526-123445](https://user-images.githubusercontent.com/64093255/119719622-a02cdd80-be2e-11eb-961b-2b6d590faf7b.png)
![Screenshot_20210526-122552](https://user-images.githubusercontent.com/64093255/119719629-a1f6a100-be2e-11eb-85fd-ff49bd384211.png)
![Screenshot_20210526-122818](https://user-images.githubusercontent.com/64093255/119719634-a3c06480-be2e-11eb-8796-c66b5bed1592.png)
![Screenshot_20210526-123202](https://user-images.githubusercontent.com/64093255/119719638-a58a2800-be2e-11eb-9d89-31e38b92e4a7.png)
![Screenshot_20210526-124840](https://user-images.githubusercontent.com/64093255/119719646-a753eb80-be2e-11eb-9976-a43159ce5da1.png)

@librehat I compiled that one, okay?

**Comment by ayesumit** [comment]
Looks Nice!

**Comment by Yisus7u7** [comment]
> Looks Nice!

![Screenshot_20210603-174013](https://user-images.githubusercontent.com/64093255/120810494-b7e02200-c510-11eb-80e2-38bd75f4074b.png)

Audacious was added, this will close

pkg install audacious
