### ISSUE TITLE
How to run python pyqt5 apps in this environment??

### ISSUE THREAD

**Issue by bajrangCoder** [Yisus7u7/termux-desktop-lxqt#20]
I want to install `pyqt5` python module on this termux desktop environment. 
I tried ``` pip install PyQt5 ``` but it failed. 
Please anyone help me........

**Comment by JesusChapman** [comment]
> I want to install `pyqt5` python module on this termux desktop environment. I tried `pip install PyQt5` but it failed. Please anyone help me........

It is currently not possible to use Pyqt5 in termux, you can only use tkinter, python-fltk, pyopengl, PySimpleGUI and pysdl2

**Comment by bajrangCoder** [comment]
Is it possible to install eel python module???

**Comment by JesusChapman** [comment]
> Is it possible to install eel python module???

pyqt5 no
