### ISSUE TITLE
How to install kivy?

### ISSUE THREAD

**Issue by bajrangCoder** [Yisus7u7/termux-desktop-lxqt#21]
I want to install `kivy` on `termux-desktop-lxqt` , I use ubuntu so I installed kivy using `apt install python3-kivy`. But while running my first hello World program it shows some messages and error.

`
[INFO   ] [Logger      ] Record log in /root/.kivy/logs/kivy_22-01-25_19.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/usr/local/lib/python3.9/dist-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [Window      ] Provider: x11(['window_sdl2'] ignored)
No matching FB config found
`

**Comment by JesusChapman** [comment]
> I want to install `kivy` on `termux-desktop-lxqt` , I use ubuntu so I installed kivy using `apt install python3-kivy`. But while running my first hello World program it shows some messages and error.
> 
> `[INFO ] [Logger ] Record log in /root/.kivy/logs/kivy_22-01-25_19.txt [INFO ] [Kivy ] v2.0.0 [INFO ] [Kivy ] Installed at "/usr/local/lib/python3.9/dist-packages/kivy/__init__.py" [INFO ] [Python ] v3.9.7 (default, Sep 10 2021, 14:59:43) [GCC 11.2.0] [INFO ] [Python ] Interpreter at "/usr/bin/python3" [INFO ] [Factory ] 186 symbols loaded [INFO ] [Image ] Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored) [INFO ] [Text ] Provider: sdl2 [INFO ] [Window ] Provider: sdl2 [INFO ] [Window ] Provider: x11(['window_sdl2'] ignored) No matching FB config found`

Requires hardware acceleration (OpenGL) to work
